services:
  postgres:
    restart: 'always'
    image: postgres:15-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "wallet_app_db_user"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '5432:5432'

volumes:
  postgresdb:
