// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeliwei930/walletassignment/ent/ledger"
	"github.com/leeliwei930/walletassignment/ent/wallet"
)

// LedgerCreate is the builder for creating a Ledger entity.
type LedgerCreate struct {
	config
	mutation *LedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWalletID sets the "wallet_id" field.
func (lc *LedgerCreate) SetWalletID(u uuid.UUID) *LedgerCreate {
	lc.mutation.SetWalletID(u)
	return lc
}

// SetAmount sets the "amount" field.
func (lc *LedgerCreate) SetAmount(i int) *LedgerCreate {
	lc.mutation.SetAmount(i)
	return lc
}

// SetDescription sets the "description" field.
func (lc *LedgerCreate) SetDescription(s string) *LedgerCreate {
	lc.mutation.SetDescription(s)
	return lc
}

// SetRecipientReferenceNote sets the "recipient_reference_note" field.
func (lc *LedgerCreate) SetRecipientReferenceNote(s string) *LedgerCreate {
	lc.mutation.SetRecipientReferenceNote(s)
	return lc
}

// SetNillableRecipientReferenceNote sets the "recipient_reference_note" field if the given value is not nil.
func (lc *LedgerCreate) SetNillableRecipientReferenceNote(s *string) *LedgerCreate {
	if s != nil {
		lc.SetRecipientReferenceNote(*s)
	}
	return lc
}

// SetTransactionType sets the "transaction_type" field.
func (lc *LedgerCreate) SetTransactionType(s string) *LedgerCreate {
	lc.mutation.SetTransactionType(s)
	return lc
}

// SetCreatedAt sets the "created_at" field.
func (lc *LedgerCreate) SetCreatedAt(t time.Time) *LedgerCreate {
	lc.mutation.SetCreatedAt(t)
	return lc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lc *LedgerCreate) SetNillableCreatedAt(t *time.Time) *LedgerCreate {
	if t != nil {
		lc.SetCreatedAt(*t)
	}
	return lc
}

// SetUpdatedAt sets the "updated_at" field.
func (lc *LedgerCreate) SetUpdatedAt(t time.Time) *LedgerCreate {
	lc.mutation.SetUpdatedAt(t)
	return lc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (lc *LedgerCreate) SetNillableUpdatedAt(t *time.Time) *LedgerCreate {
	if t != nil {
		lc.SetUpdatedAt(*t)
	}
	return lc
}

// SetID sets the "id" field.
func (lc *LedgerCreate) SetID(u uuid.UUID) *LedgerCreate {
	lc.mutation.SetID(u)
	return lc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lc *LedgerCreate) SetNillableID(u *uuid.UUID) *LedgerCreate {
	if u != nil {
		lc.SetID(*u)
	}
	return lc
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (lc *LedgerCreate) SetWallet(w *Wallet) *LedgerCreate {
	return lc.SetWalletID(w.ID)
}

// Mutation returns the LedgerMutation object of the builder.
func (lc *LedgerCreate) Mutation() *LedgerMutation {
	return lc.mutation
}

// Save creates the Ledger in the database.
func (lc *LedgerCreate) Save(ctx context.Context) (*Ledger, error) {
	lc.defaults()
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LedgerCreate) SaveX(ctx context.Context) *Ledger {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LedgerCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LedgerCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *LedgerCreate) defaults() {
	if _, ok := lc.mutation.CreatedAt(); !ok {
		v := ledger.DefaultCreatedAt()
		lc.mutation.SetCreatedAt(v)
	}
	if _, ok := lc.mutation.UpdatedAt(); !ok {
		v := ledger.DefaultUpdatedAt()
		lc.mutation.SetUpdatedAt(v)
	}
	if _, ok := lc.mutation.ID(); !ok {
		v := ledger.DefaultID()
		lc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LedgerCreate) check() error {
	if _, ok := lc.mutation.WalletID(); !ok {
		return &ValidationError{Name: "wallet_id", err: errors.New(`ent: missing required field "Ledger.wallet_id"`)}
	}
	if _, ok := lc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Ledger.amount"`)}
	}
	if v, ok := lc.mutation.Amount(); ok {
		if err := ledger.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Ledger.amount": %w`, err)}
		}
	}
	if _, ok := lc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Ledger.description"`)}
	}
	if _, ok := lc.mutation.TransactionType(); !ok {
		return &ValidationError{Name: "transaction_type", err: errors.New(`ent: missing required field "Ledger.transaction_type"`)}
	}
	if _, ok := lc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ledger.created_at"`)}
	}
	if _, ok := lc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ledger.updated_at"`)}
	}
	if len(lc.mutation.WalletIDs()) == 0 {
		return &ValidationError{Name: "wallet", err: errors.New(`ent: missing required edge "Ledger.wallet"`)}
	}
	return nil
}

func (lc *LedgerCreate) sqlSave(ctx context.Context) (*Ledger, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LedgerCreate) createSpec() (*Ledger, *sqlgraph.CreateSpec) {
	var (
		_node = &Ledger{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(ledger.Table, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = lc.conflict
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := lc.mutation.Amount(); ok {
		_spec.SetField(ledger.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := lc.mutation.Description(); ok {
		_spec.SetField(ledger.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := lc.mutation.RecipientReferenceNote(); ok {
		_spec.SetField(ledger.FieldRecipientReferenceNote, field.TypeString, value)
		_node.RecipientReferenceNote = &value
	}
	if value, ok := lc.mutation.TransactionType(); ok {
		_spec.SetField(ledger.FieldTransactionType, field.TypeString, value)
		_node.TransactionType = value
	}
	if value, ok := lc.mutation.CreatedAt(); ok {
		_spec.SetField(ledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := lc.mutation.UpdatedAt(); ok {
		_spec.SetField(ledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := lc.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledger.WalletTable,
			Columns: []string{ledger.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WalletID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ledger.Create().
//		SetWalletID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LedgerUpsert) {
//			SetWalletID(v+v).
//		}).
//		Exec(ctx)
func (lc *LedgerCreate) OnConflict(opts ...sql.ConflictOption) *LedgerUpsertOne {
	lc.conflict = opts
	return &LedgerUpsertOne{
		create: lc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ledger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (lc *LedgerCreate) OnConflictColumns(columns ...string) *LedgerUpsertOne {
	lc.conflict = append(lc.conflict, sql.ConflictColumns(columns...))
	return &LedgerUpsertOne{
		create: lc,
	}
}

type (
	// LedgerUpsertOne is the builder for "upsert"-ing
	//  one Ledger node.
	LedgerUpsertOne struct {
		create *LedgerCreate
	}

	// LedgerUpsert is the "OnConflict" setter.
	LedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetWalletID sets the "wallet_id" field.
func (u *LedgerUpsert) SetWalletID(v uuid.UUID) *LedgerUpsert {
	u.Set(ledger.FieldWalletID, v)
	return u
}

// UpdateWalletID sets the "wallet_id" field to the value that was provided on create.
func (u *LedgerUpsert) UpdateWalletID() *LedgerUpsert {
	u.SetExcluded(ledger.FieldWalletID)
	return u
}

// SetAmount sets the "amount" field.
func (u *LedgerUpsert) SetAmount(v int) *LedgerUpsert {
	u.Set(ledger.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LedgerUpsert) UpdateAmount() *LedgerUpsert {
	u.SetExcluded(ledger.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *LedgerUpsert) AddAmount(v int) *LedgerUpsert {
	u.Add(ledger.FieldAmount, v)
	return u
}

// SetDescription sets the "description" field.
func (u *LedgerUpsert) SetDescription(v string) *LedgerUpsert {
	u.Set(ledger.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LedgerUpsert) UpdateDescription() *LedgerUpsert {
	u.SetExcluded(ledger.FieldDescription)
	return u
}

// SetRecipientReferenceNote sets the "recipient_reference_note" field.
func (u *LedgerUpsert) SetRecipientReferenceNote(v string) *LedgerUpsert {
	u.Set(ledger.FieldRecipientReferenceNote, v)
	return u
}

// UpdateRecipientReferenceNote sets the "recipient_reference_note" field to the value that was provided on create.
func (u *LedgerUpsert) UpdateRecipientReferenceNote() *LedgerUpsert {
	u.SetExcluded(ledger.FieldRecipientReferenceNote)
	return u
}

// ClearRecipientReferenceNote clears the value of the "recipient_reference_note" field.
func (u *LedgerUpsert) ClearRecipientReferenceNote() *LedgerUpsert {
	u.SetNull(ledger.FieldRecipientReferenceNote)
	return u
}

// SetTransactionType sets the "transaction_type" field.
func (u *LedgerUpsert) SetTransactionType(v string) *LedgerUpsert {
	u.Set(ledger.FieldTransactionType, v)
	return u
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *LedgerUpsert) UpdateTransactionType() *LedgerUpsert {
	u.SetExcluded(ledger.FieldTransactionType)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LedgerUpsert) SetCreatedAt(v time.Time) *LedgerUpsert {
	u.Set(ledger.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LedgerUpsert) UpdateCreatedAt() *LedgerUpsert {
	u.SetExcluded(ledger.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LedgerUpsert) SetUpdatedAt(v time.Time) *LedgerUpsert {
	u.Set(ledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LedgerUpsert) UpdateUpdatedAt() *LedgerUpsert {
	u.SetExcluded(ledger.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Ledger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ledger.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LedgerUpsertOne) UpdateNewValues() *LedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ledger.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ledger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LedgerUpsertOne) Ignore() *LedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LedgerUpsertOne) DoNothing() *LedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LedgerCreate.OnConflict
// documentation for more info.
func (u *LedgerUpsertOne) Update(set func(*LedgerUpsert)) *LedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetWalletID sets the "wallet_id" field.
func (u *LedgerUpsertOne) SetWalletID(v uuid.UUID) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.SetWalletID(v)
	})
}

// UpdateWalletID sets the "wallet_id" field to the value that was provided on create.
func (u *LedgerUpsertOne) UpdateWalletID() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateWalletID()
	})
}

// SetAmount sets the "amount" field.
func (u *LedgerUpsertOne) SetAmount(v int) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *LedgerUpsertOne) AddAmount(v int) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LedgerUpsertOne) UpdateAmount() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetDescription sets the "description" field.
func (u *LedgerUpsertOne) SetDescription(v string) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LedgerUpsertOne) UpdateDescription() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateDescription()
	})
}

// SetRecipientReferenceNote sets the "recipient_reference_note" field.
func (u *LedgerUpsertOne) SetRecipientReferenceNote(v string) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.SetRecipientReferenceNote(v)
	})
}

// UpdateRecipientReferenceNote sets the "recipient_reference_note" field to the value that was provided on create.
func (u *LedgerUpsertOne) UpdateRecipientReferenceNote() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateRecipientReferenceNote()
	})
}

// ClearRecipientReferenceNote clears the value of the "recipient_reference_note" field.
func (u *LedgerUpsertOne) ClearRecipientReferenceNote() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.ClearRecipientReferenceNote()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *LedgerUpsertOne) SetTransactionType(v string) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *LedgerUpsertOne) UpdateTransactionType() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateTransactionType()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LedgerUpsertOne) SetCreatedAt(v time.Time) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LedgerUpsertOne) UpdateCreatedAt() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LedgerUpsertOne) SetUpdatedAt(v time.Time) *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LedgerUpsertOne) UpdateUpdatedAt() *LedgerUpsertOne {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LedgerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LedgerUpsertOne.ID is not supported by MySQL driver. Use LedgerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LedgerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LedgerCreateBulk is the builder for creating many Ledger entities in bulk.
type LedgerCreateBulk struct {
	config
	err      error
	builders []*LedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the Ledger entities in the database.
func (lcb *LedgerCreateBulk) Save(ctx context.Context) ([]*Ledger, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Ledger, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = lcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LedgerCreateBulk) SaveX(ctx context.Context) []*Ledger {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LedgerCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ledger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LedgerUpsert) {
//			SetWalletID(v+v).
//		}).
//		Exec(ctx)
func (lcb *LedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *LedgerUpsertBulk {
	lcb.conflict = opts
	return &LedgerUpsertBulk{
		create: lcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ledger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (lcb *LedgerCreateBulk) OnConflictColumns(columns ...string) *LedgerUpsertBulk {
	lcb.conflict = append(lcb.conflict, sql.ConflictColumns(columns...))
	return &LedgerUpsertBulk{
		create: lcb,
	}
}

// LedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of Ledger nodes.
type LedgerUpsertBulk struct {
	create *LedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Ledger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ledger.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LedgerUpsertBulk) UpdateNewValues() *LedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ledger.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ledger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LedgerUpsertBulk) Ignore() *LedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LedgerUpsertBulk) DoNothing() *LedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LedgerCreateBulk.OnConflict
// documentation for more info.
func (u *LedgerUpsertBulk) Update(set func(*LedgerUpsert)) *LedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetWalletID sets the "wallet_id" field.
func (u *LedgerUpsertBulk) SetWalletID(v uuid.UUID) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.SetWalletID(v)
	})
}

// UpdateWalletID sets the "wallet_id" field to the value that was provided on create.
func (u *LedgerUpsertBulk) UpdateWalletID() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateWalletID()
	})
}

// SetAmount sets the "amount" field.
func (u *LedgerUpsertBulk) SetAmount(v int) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *LedgerUpsertBulk) AddAmount(v int) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LedgerUpsertBulk) UpdateAmount() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetDescription sets the "description" field.
func (u *LedgerUpsertBulk) SetDescription(v string) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LedgerUpsertBulk) UpdateDescription() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateDescription()
	})
}

// SetRecipientReferenceNote sets the "recipient_reference_note" field.
func (u *LedgerUpsertBulk) SetRecipientReferenceNote(v string) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.SetRecipientReferenceNote(v)
	})
}

// UpdateRecipientReferenceNote sets the "recipient_reference_note" field to the value that was provided on create.
func (u *LedgerUpsertBulk) UpdateRecipientReferenceNote() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateRecipientReferenceNote()
	})
}

// ClearRecipientReferenceNote clears the value of the "recipient_reference_note" field.
func (u *LedgerUpsertBulk) ClearRecipientReferenceNote() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.ClearRecipientReferenceNote()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *LedgerUpsertBulk) SetTransactionType(v string) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *LedgerUpsertBulk) UpdateTransactionType() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateTransactionType()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LedgerUpsertBulk) SetCreatedAt(v time.Time) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LedgerUpsertBulk) UpdateCreatedAt() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LedgerUpsertBulk) SetUpdatedAt(v time.Time) *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LedgerUpsertBulk) UpdateUpdatedAt() *LedgerUpsertBulk {
	return u.Update(func(s *LedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
