// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeliwei930/walletassignment/ent/ledger"
	"github.com/leeliwei930/walletassignment/ent/predicate"
	"github.com/leeliwei930/walletassignment/ent/user"
	"github.com/leeliwei930/walletassignment/ent/wallet"
)

// WalletUpdate is the builder for updating Wallet entities.
type WalletUpdate struct {
	config
	hooks    []Hook
	mutation *WalletMutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (wu *WalletUpdate) Where(ps ...predicate.Wallet) *WalletUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUserID sets the "user_id" field.
func (wu *WalletUpdate) SetUserID(u uuid.UUID) *WalletUpdate {
	wu.mutation.SetUserID(u)
	return wu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableUserID(u *uuid.UUID) *WalletUpdate {
	if u != nil {
		wu.SetUserID(*u)
	}
	return wu
}

// SetBalance sets the "balance" field.
func (wu *WalletUpdate) SetBalance(i int) *WalletUpdate {
	wu.mutation.ResetBalance()
	wu.mutation.SetBalance(i)
	return wu
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableBalance(i *int) *WalletUpdate {
	if i != nil {
		wu.SetBalance(*i)
	}
	return wu
}

// AddBalance adds i to the "balance" field.
func (wu *WalletUpdate) AddBalance(i int) *WalletUpdate {
	wu.mutation.AddBalance(i)
	return wu
}

// SetCurrencyCode sets the "currency_code" field.
func (wu *WalletUpdate) SetCurrencyCode(s string) *WalletUpdate {
	wu.mutation.SetCurrencyCode(s)
	return wu
}

// SetNillableCurrencyCode sets the "currency_code" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableCurrencyCode(s *string) *WalletUpdate {
	if s != nil {
		wu.SetCurrencyCode(*s)
	}
	return wu
}

// SetDecimalPlaces sets the "decimal_places" field.
func (wu *WalletUpdate) SetDecimalPlaces(i int) *WalletUpdate {
	wu.mutation.ResetDecimalPlaces()
	wu.mutation.SetDecimalPlaces(i)
	return wu
}

// SetNillableDecimalPlaces sets the "decimal_places" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableDecimalPlaces(i *int) *WalletUpdate {
	if i != nil {
		wu.SetDecimalPlaces(*i)
	}
	return wu
}

// AddDecimalPlaces adds i to the "decimal_places" field.
func (wu *WalletUpdate) AddDecimalPlaces(i int) *WalletUpdate {
	wu.mutation.AddDecimalPlaces(i)
	return wu
}

// SetCreatedAt sets the "created_at" field.
func (wu *WalletUpdate) SetCreatedAt(t time.Time) *WalletUpdate {
	wu.mutation.SetCreatedAt(t)
	return wu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableCreatedAt(t *time.Time) *WalletUpdate {
	if t != nil {
		wu.SetCreatedAt(*t)
	}
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WalletUpdate) SetUpdatedAt(t time.Time) *WalletUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetUser sets the "user" edge to the User entity.
func (wu *WalletUpdate) SetUser(u *User) *WalletUpdate {
	return wu.SetUserID(u.ID)
}

// AddLedgerIDs adds the "ledgers" edge to the Ledger entity by IDs.
func (wu *WalletUpdate) AddLedgerIDs(ids ...uuid.UUID) *WalletUpdate {
	wu.mutation.AddLedgerIDs(ids...)
	return wu
}

// AddLedgers adds the "ledgers" edges to the Ledger entity.
func (wu *WalletUpdate) AddLedgers(l ...*Ledger) *WalletUpdate {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return wu.AddLedgerIDs(ids...)
}

// Mutation returns the WalletMutation object of the builder.
func (wu *WalletUpdate) Mutation() *WalletMutation {
	return wu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (wu *WalletUpdate) ClearUser() *WalletUpdate {
	wu.mutation.ClearUser()
	return wu
}

// ClearLedgers clears all "ledgers" edges to the Ledger entity.
func (wu *WalletUpdate) ClearLedgers() *WalletUpdate {
	wu.mutation.ClearLedgers()
	return wu
}

// RemoveLedgerIDs removes the "ledgers" edge to Ledger entities by IDs.
func (wu *WalletUpdate) RemoveLedgerIDs(ids ...uuid.UUID) *WalletUpdate {
	wu.mutation.RemoveLedgerIDs(ids...)
	return wu
}

// RemoveLedgers removes "ledgers" edges to Ledger entities.
func (wu *WalletUpdate) RemoveLedgers(l ...*Ledger) *WalletUpdate {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return wu.RemoveLedgerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WalletUpdate) Save(ctx context.Context) (int, error) {
	wu.defaults()
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WalletUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WalletUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WalletUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WalletUpdate) defaults() {
	if _, ok := wu.mutation.UpdatedAt(); !ok {
		v := wallet.UpdateDefaultUpdatedAt()
		wu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WalletUpdate) check() error {
	if wu.mutation.UserCleared() && len(wu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Wallet.user"`)
	}
	return nil
}

func (wu *WalletUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Balance(); ok {
		_spec.SetField(wallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedBalance(); ok {
		_spec.AddField(wallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := wu.mutation.CurrencyCode(); ok {
		_spec.SetField(wallet.FieldCurrencyCode, field.TypeString, value)
	}
	if value, ok := wu.mutation.DecimalPlaces(); ok {
		_spec.SetField(wallet.FieldDecimalPlaces, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedDecimalPlaces(); ok {
		_spec.AddField(wallet.FieldDecimalPlaces, field.TypeInt, value)
	}
	if value, ok := wu.mutation.CreatedAt(); ok {
		_spec.SetField(wallet.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if wu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallet.UserTable,
			Columns: []string{wallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallet.UserTable,
			Columns: []string{wallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.LedgersTable,
			Columns: []string{wallet.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !wu.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.LedgersTable,
			Columns: []string{wallet.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.LedgersTable,
			Columns: []string{wallet.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WalletUpdateOne is the builder for updating a single Wallet entity.
type WalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletMutation
}

// SetUserID sets the "user_id" field.
func (wuo *WalletUpdateOne) SetUserID(u uuid.UUID) *WalletUpdateOne {
	wuo.mutation.SetUserID(u)
	return wuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableUserID(u *uuid.UUID) *WalletUpdateOne {
	if u != nil {
		wuo.SetUserID(*u)
	}
	return wuo
}

// SetBalance sets the "balance" field.
func (wuo *WalletUpdateOne) SetBalance(i int) *WalletUpdateOne {
	wuo.mutation.ResetBalance()
	wuo.mutation.SetBalance(i)
	return wuo
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableBalance(i *int) *WalletUpdateOne {
	if i != nil {
		wuo.SetBalance(*i)
	}
	return wuo
}

// AddBalance adds i to the "balance" field.
func (wuo *WalletUpdateOne) AddBalance(i int) *WalletUpdateOne {
	wuo.mutation.AddBalance(i)
	return wuo
}

// SetCurrencyCode sets the "currency_code" field.
func (wuo *WalletUpdateOne) SetCurrencyCode(s string) *WalletUpdateOne {
	wuo.mutation.SetCurrencyCode(s)
	return wuo
}

// SetNillableCurrencyCode sets the "currency_code" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableCurrencyCode(s *string) *WalletUpdateOne {
	if s != nil {
		wuo.SetCurrencyCode(*s)
	}
	return wuo
}

// SetDecimalPlaces sets the "decimal_places" field.
func (wuo *WalletUpdateOne) SetDecimalPlaces(i int) *WalletUpdateOne {
	wuo.mutation.ResetDecimalPlaces()
	wuo.mutation.SetDecimalPlaces(i)
	return wuo
}

// SetNillableDecimalPlaces sets the "decimal_places" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableDecimalPlaces(i *int) *WalletUpdateOne {
	if i != nil {
		wuo.SetDecimalPlaces(*i)
	}
	return wuo
}

// AddDecimalPlaces adds i to the "decimal_places" field.
func (wuo *WalletUpdateOne) AddDecimalPlaces(i int) *WalletUpdateOne {
	wuo.mutation.AddDecimalPlaces(i)
	return wuo
}

// SetCreatedAt sets the "created_at" field.
func (wuo *WalletUpdateOne) SetCreatedAt(t time.Time) *WalletUpdateOne {
	wuo.mutation.SetCreatedAt(t)
	return wuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableCreatedAt(t *time.Time) *WalletUpdateOne {
	if t != nil {
		wuo.SetCreatedAt(*t)
	}
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WalletUpdateOne) SetUpdatedAt(t time.Time) *WalletUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetUser sets the "user" edge to the User entity.
func (wuo *WalletUpdateOne) SetUser(u *User) *WalletUpdateOne {
	return wuo.SetUserID(u.ID)
}

// AddLedgerIDs adds the "ledgers" edge to the Ledger entity by IDs.
func (wuo *WalletUpdateOne) AddLedgerIDs(ids ...uuid.UUID) *WalletUpdateOne {
	wuo.mutation.AddLedgerIDs(ids...)
	return wuo
}

// AddLedgers adds the "ledgers" edges to the Ledger entity.
func (wuo *WalletUpdateOne) AddLedgers(l ...*Ledger) *WalletUpdateOne {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return wuo.AddLedgerIDs(ids...)
}

// Mutation returns the WalletMutation object of the builder.
func (wuo *WalletUpdateOne) Mutation() *WalletMutation {
	return wuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (wuo *WalletUpdateOne) ClearUser() *WalletUpdateOne {
	wuo.mutation.ClearUser()
	return wuo
}

// ClearLedgers clears all "ledgers" edges to the Ledger entity.
func (wuo *WalletUpdateOne) ClearLedgers() *WalletUpdateOne {
	wuo.mutation.ClearLedgers()
	return wuo
}

// RemoveLedgerIDs removes the "ledgers" edge to Ledger entities by IDs.
func (wuo *WalletUpdateOne) RemoveLedgerIDs(ids ...uuid.UUID) *WalletUpdateOne {
	wuo.mutation.RemoveLedgerIDs(ids...)
	return wuo
}

// RemoveLedgers removes "ledgers" edges to Ledger entities.
func (wuo *WalletUpdateOne) RemoveLedgers(l ...*Ledger) *WalletUpdateOne {
	ids := make([]uuid.UUID, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return wuo.RemoveLedgerIDs(ids...)
}

// Where appends a list predicates to the WalletUpdate builder.
func (wuo *WalletUpdateOne) Where(ps ...predicate.Wallet) *WalletUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WalletUpdateOne) Select(field string, fields ...string) *WalletUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Wallet entity.
func (wuo *WalletUpdateOne) Save(ctx context.Context) (*Wallet, error) {
	wuo.defaults()
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WalletUpdateOne) SaveX(ctx context.Context) *Wallet {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WalletUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WalletUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WalletUpdateOne) defaults() {
	if _, ok := wuo.mutation.UpdatedAt(); !ok {
		v := wallet.UpdateDefaultUpdatedAt()
		wuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WalletUpdateOne) check() error {
	if wuo.mutation.UserCleared() && len(wuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Wallet.user"`)
	}
	return nil
}

func (wuo *WalletUpdateOne) sqlSave(ctx context.Context) (_node *Wallet, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Wallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallet.FieldID)
		for _, f := range fields {
			if !wallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Balance(); ok {
		_spec.SetField(wallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedBalance(); ok {
		_spec.AddField(wallet.FieldBalance, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.CurrencyCode(); ok {
		_spec.SetField(wallet.FieldCurrencyCode, field.TypeString, value)
	}
	if value, ok := wuo.mutation.DecimalPlaces(); ok {
		_spec.SetField(wallet.FieldDecimalPlaces, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedDecimalPlaces(); ok {
		_spec.AddField(wallet.FieldDecimalPlaces, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.CreatedAt(); ok {
		_spec.SetField(wallet.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if wuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallet.UserTable,
			Columns: []string{wallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallet.UserTable,
			Columns: []string{wallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.LedgersTable,
			Columns: []string{wallet.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !wuo.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.LedgersTable,
			Columns: []string{wallet.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.LedgersTable,
			Columns: []string{wallet.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Wallet{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
