// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ledger is the predicate function for ledger builders.
type Ledger func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)
